site_name: Tufts TTS Research Technology Tufts HPC Documentation - Beta 
repo_url: https://github.com/tuftsdatalab/rt_hpc_documentation
edit_uri: blob/main/docs/

theme:
  name: material
  features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - content.action.edit 
        - navigation.footer
        - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: 'img/logo3.png'
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      prerequisite: octicons/beaker-16
      quote: octicons/quote-16
        
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
     
extra_css:
    - stylesheets/extra.css
    
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

nav:
    - About : 
        - Introduction: index.md
        - News: 
            - "2023": news/2023_news.md
            - "2022": news/2022_news.md
    - HPC User Guide : 
        - Introduction To The Cluster:
            - "What Is The Cluster?": hpc_user_guide/what-is-the-cluster.md
            - "Request an Account": hpc_user_guide/request-account.md
            - "Navigate To The Cluster": hpc_user_guide/navigate-to-cluster.md
            - "File Transfer": hpc_user_guide/file-transfer.md
        - Cluster Resources:
            - "Cluster Storage Request": hpc_user_guide/new_cluster_storage.md
            - "Cluster Storage Increase Request": hpc_user_guide/cluster_storage_increase.md
            - "Compute Resources": hpc_user_guide/compute-resources.md
            - "Software On The Cluster": hpc_user_guide/software-cluster.md
        - Introduction To SLURM:
            - "Interactive Session": hpc_user_guide/interactive-session.md
            - "Submitting A Batch Job": hpc_user_guide/batch-job.md
            - "Checking Job Status": hpc_user_guide/job-status.md
        - HPC Services:
            - "HPC Services": hpc_user_guide/hpc_services.md
    - HPC Software/Tools: 
        - Available HPC Tools: hpc_tools/all_hpc_tools.md
        - Python: 
            - "Python Interactive Session": hpc_tools/python-modules.md
            - "JupyterLab": hpc_tools/python-jupyter.md
            - "Conda Environments": hpc_tools/python-conda.md
        - R: 
            - "R Interactive Session": hpc_tools/r-interactive.md
            - "R Batch Jobs": hpc_tools/r-batch.md
            - "RStudio OnDemand": hpc_tools/r-rstudio.md
        - Misc:
            - "GitHub": hpc_tools/github.md
            - "Rclone": hpc_tools/rclone.md
            - "Containers": hpc_tools/containers.md
            - "Nextflow": hpc_tools/nextflow.md
            - "Parallel": hpc_tools/parallel.md 
            - "API (Application Programming Interface)": hpc_tools/api.md
            - "dbGAP Downloads": hpc_tools/dbgap.md
            - "Tufts VDI": hpc_tools/vdi.md
            - "RStore": hpc_tools/rstore.md
    - Unix/R/Python Tutorials:
        - Introduction: programming_languages/unix_r_python.md
        - Unix:
            - Intro To Unix: 
                - "Intro To Linux": programming_languages/intro_to_unix/01_intro-to-unix.md
                - "Starting with Shell": programming_languages/intro_to_unix/02_start-w-shell.md
                - "Bash Parameters": programming_languages/intro_to_unix/03_bash-parameters.md
                - "Shell Navigation": programming_languages/intro_to_unix/04_shell-navigation.md
                - "Creating & Manipulating Files": programming_languages/intro_to_unix/05_create-manipulate-files.md
                - "Going Home": programming_languages/intro_to_unix/06_going-home.md
                - "Running an Interactive Session": programming_languages/intro_to_unix/07_running-interactive.md
                - "Example with BLAST": programming_languages/intro_to_unix/08_blast-example.md
                - "BLAST Batch Script": programming_languages/intro_to_unix/09_blast-batch.md
        - R:
            - Intro To R: 
                - "Introduction To R OnDemand": programming_languages/intro_r_studio/01_r-intro.md
                - "R Basics": programming_languages/intro_r_studio/02_r-ondemand.md
                - "Data Structures": programming_languages/intro_r_studio/03_r-workshop-markdown.md
        - Python:
            - Intro To Python:
                - "Introduction To Python OnDemand": programming_languages/intro_to_python/01_python-ondemand.md
                - "Variables & Data Types": programming_languages/intro_to_python/02_variables-data-types.md
                - "Libraries & Data Frames": programming_languages/intro_to_python/03_libraries-data-frames.md
                - "Plotting with Plotly": programming_languages/intro_to_python/04_plotting-plotly.md
                - "Lists": programming_languages/intro_to_python/05_lists.md
                - "Loops & Conditionals": programming_languages/intro_to_python/06_loops-conditionals.md
                - "Functions & Scope": programming_languages/intro_to_python/07_functions-scope.md 
    - RStore:
        - Description: RStore/Description.md 
        - Requests: RStore/Requests.md 
        
               
              
      
    
        
